"use client";

import { FormEvent, useState } from "react";

type Errors = Partial<Record<"name" | "email" | "message" | "url", string>>;
const field = "mt-2 min-h-12 w-full rounded-xl border border-[#BBCAC4] bg-white px-4 py-3 outline-none focus:border-[#3F6B5B] focus:ring-2 focus:ring-[#3F6B5B]/25";

export default function ContactSection() {
  const [complete, setComplete] = useState(false); const [submitting, setSubmitting] = useState(false); const [errors, setErrors] = useState<Errors>({});
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (submitting) return; setSubmitting(true); const data = new FormData(event.currentTarget); const next: Errors = {}; const name = String(data.get("name") || "").trim(); const email = String(data.get("email") || "").trim(); const message = String(data.get("message") || "").trim(); const url = String(data.get("url") || "").trim(); if (!name) next.name = "お名前を入力してください。"; if (!email) next.email = "メールアドレスを入力してください。"; else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) next.email = "正しい形式で入力してください。"; if (!message) next.message = "ご相談内容を入力してください。"; if (url) { try { const parsed = new URL(url); if (!(["http:", "https:"] as string[]).includes(parsed.protocol)) throw new Error("invalid protocol"); } catch { next.url = "https:// から始まるURLを入力してください。"; } } setErrors(next); if (Object.keys(next).length === 0) setComplete(true); setSubmitting(false); };
  return <section id="contact" className="hws-section bg-[#EAF2EE]"><div className="hws-container max-w-4xl"><p className="hws-kicker">CONTACT</p><h2 className="hws-heading">無料相談デモフォーム</h2><p className="mt-4 rounded-xl border border-[#D9834E]/40 bg-white p-4 font-medium">このフォームはポートフォリオ用のデモです。<br />入力内容は実際には送信されません。</p>{complete ? <div className="mt-8 rounded-3xl bg-white p-8 text-center shadow-sm" role="status"><h3 className="text-2xl font-bold text-[#2F5145]">入力ありがとうございました。</h3><p className="mt-4 leading-7">このフォームはポートフォリオ用のデモのため、<br />実際の送信は行われていません。</p><button type="button" onClick={() => { setComplete(false); setErrors({}); }} className="hws-secondary mt-6">入力画面へ戻る</button></div> : <form className="mt-8 grid gap-5 rounded-3xl bg-white p-5 shadow-sm md:grid-cols-2 md:p-8" onSubmit={submit} noValidate>
    <Text name="name" label="お名前" required maxLength={100} error={errors.name} /><Text name="business" label="屋号・事業名" maxLength={100} /><Text name="email" label="メールアドレス" type="email" required error={errors.email} /><Text name="industry" label="業種" maxLength={100} />
    <Select name="service" label="希望する制作内容" options={["LP制作", "小規模ホームページ", "既存サイト改善", "まだ決まっていない"]} /><Select name="budget" label="ご予算" options={["5万円未満", "5万〜10万円", "10万〜20万円", "20万〜30万円", "30万円以上", "まだ決まっていない"]} /><Select name="timing" label="希望時期" options={["1か月以内", "2〜3か月以内", "3か月以降", "まだ決まっていない"]} /><Text name="url" label="現在のWebサイトURL" type="url" error={errors.url} />
    <label className="md:col-span-2"><span className="font-bold">ご相談内容 <b className="text-[#A84A21]">（必須）</b></span><textarea name="message" maxLength={2000} aria-invalid={Boolean(errors.message)} aria-describedby={errors.message ? "message-error" : undefined} className={`${field} min-h-40`} />{errors.message && <span id="message-error" className="mt-1 block text-sm font-medium text-[#A33A2B]">エラー：{errors.message}</span>}</label>
    <button type="submit" disabled={submitting} className="hws-button md:col-span-2 disabled:opacity-60">入力内容を確認して完了する（デモ）</button>
  </form>}</div></section>;
}
function Text({ name, label, required, error, type = "text", maxLength }: { name: string; label: string; required?: boolean; error?: string; type?: string; maxLength?: number }) { return <label><span className="font-bold">{label} <b className={required ? "text-[#A84A21]" : "font-normal text-[#4B5563]"}>（{required ? "必須" : "任意"}）</b></span><input name={name} type={type} required={required} maxLength={maxLength} aria-invalid={Boolean(error)} aria-describedby={error ? `${name}-error` : undefined} className={field} />{error && <span id={`${name}-error`} className="mt-1 block text-sm font-medium text-[#A33A2B]">エラー：{error}</span>}</label>; }
function Select({ name, label, options }: { name: string; label: string; options: readonly string[] }) { return <label><span className="font-bold">{label} <b className="font-normal text-[#4B5563]">（任意）</b></span><select name={name} className={field}><option value="">選択してください</option>{options.map((option) => <option key={option}>{option}</option>)}</select></label>; }
