"use client";
import { FormEvent, useRef, useState } from "react";

type Key = "name" | "email" | "field" | "message" | "phone";
type Errors = Partial<Record<Key, string>>;
const inputClass = "mt-2 min-h-12 w-full rounded-xl border border-[#BCC9CC] bg-white px-4 py-3 outline-none focus:border-[#294F59] focus:ring-2 focus:ring-[#294F59]/20";

export default function AobaContactForm() {
  const [complete, setComplete] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [errors, setErrors] = useState<Errors>({});
  const formRef = useRef<HTMLFormElement>(null);
  const submit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); if (submitting) return; setSubmitting(true);
    const data = new FormData(event.currentTarget); const next: Errors = {};
    const name = String(data.get("name") || "").trim(); const email = String(data.get("email") || "").trim(); const field = String(data.get("field") || ""); const message = String(data.get("message") || "").trim(); const phone = String(data.get("phone") || "").trim();
    if (!name) next.name = "お名前を入力してください。"; if (!email) next.email = "メールアドレスを入力してください。"; else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) next.email = "正しいメール形式で入力してください。"; if (!field) next.field = "ご相談分野を選択してください。"; if (!message) next.message = "ご相談内容を入力してください。"; if (phone && !/^[0-9()+\-\s]{8,20}$/.test(phone)) next.phone = "数字とハイフンを中心に入力してください。";
    setErrors(next); const first = Object.keys(next)[0]; if (first) formRef.current?.querySelector<HTMLElement>(`[name="${first}"]`)?.focus(); else setComplete(true); setSubmitting(false);
  };
  return <section id="contact" className="aoba-section scroll-mt-16 bg-[#E8F0F1]"><div className="aoba-container max-w-4xl"><div className="aoba-section-heading"><p className="aoba-kicker">CONTACT</p><h2 className="aoba-heading">無料相談デモフォーム</h2><p className="mt-4 rounded-xl border border-[#B7864F] bg-white p-4 font-medium">このフォームはポートフォリオ用のデモです。<br />入力内容は実際には送信されません。</p></div>{complete ? <div className="mt-8 rounded-3xl bg-white p-8 text-center" role="status"><h3 className="text-2xl font-bold text-[#294F59]">入力ありがとうございました。</h3><p className="mt-4 leading-7">このフォームはポートフォリオ用のデモのため、<br />実際の相談受付や送信は行われていません。</p><button type="button" className="aoba-secondary mt-6" onClick={() => setComplete(false)}>フォームへ戻る</button></div> : <form ref={formRef} onSubmit={submit} noValidate className="aoba-contact-form mt-8 grid gap-5 rounded-3xl bg-white p-5 md:grid-cols-2 md:p-8"><Text name="name" label="お名前" required maxLength={100} error={errors.name} /><Text name="company" label="会社名・屋号" maxLength={100} /><Text name="email" label="メールアドレス" required type="email" error={errors.email} /><Text name="phone" label="電話番号" type="tel" error={errors.phone} /><Select name="field" label="ご相談分野" required error={errors.field} options={["建設業許可・各種許認可", "法人設立・事業開始", "相続・遺言", "契約書・内容証明", "在留資格・外国人雇用", "その他", "まだ分からない"]} /><Text name="prefecture" label="都道府県" /><Select name="method" label="希望する相談方法" options={["事務所での相談", "オンライン相談", "訪問相談を希望", "相談して決めたい"]} /><Select name="timing" label="希望時期" options={["できるだけ早く", "1か月以内", "2〜3か月以内", "3か月以降", "まだ決まっていない"]} /><fieldset className="md:col-span-2"><legend className="font-bold">現在お持ちの資料 <span className="font-normal text-[#5C6870]">（任意・複数選択可）</span></legend><div className="mt-3 grid gap-2 md:grid-cols-2">{["官公署から受け取った書類", "契約書・申請書のひな形", "戸籍や住民票", "会社の登記事項証明書", "決算書・確定申告書", "パスポート・在留カード", "特にない", "何が必要か分からない"].map((item) => <label key={item} className="flex min-h-11 items-center gap-2"><input type="checkbox" name="documents" value={item} />{item}</label>)}</div></fieldset><Area name="message" label="ご相談内容" required maxLength={2000} error={errors.message} /><Area name="notes" label="その他の連絡事項" maxLength={1000} /><button type="submit" disabled={submitting} className="aoba-button md:col-span-2 disabled:opacity-50">入力内容を確認して完了する（デモ）</button></form>}<div className="mt-8 rounded-2xl border border-[#D8E0E1] bg-white p-5 text-sm leading-7 text-[#5C6870]"><p>このWebサイトは、ポートフォリオ用に制作した架空の行政書士事務所サイトです。</p><p>掲載内容は一般的な例であり、実際の法律相談、行政手続き、申請受付や個別案件の判断は行っていません。実際の手続きは、資格を持つ専門家や関係機関へご確認ください。</p></div></div></section>;
}
function Text({ name, label, required, type = "text", maxLength, error }: { name: string; label: string; required?: boolean; type?: string; maxLength?: number; error?: string }) { return <label><span className="font-bold">{label} <b className={required ? "text-[#9B372C]" : "font-normal text-[#5C6870]"}>（{required ? "必須" : "任意"}）</b></span><input name={name} type={type} maxLength={maxLength} className={inputClass} aria-invalid={Boolean(error)} aria-describedby={error ? `aoba-${name}-error` : undefined} />{error && <span id={`aoba-${name}-error`} className="mt-1 block text-sm font-medium text-[#9B372C]">エラー：{error}</span>}</label>; }
function Select({ name, label, required, options, error }: { name: string; label: string; required?: boolean; options: readonly string[]; error?: string }) { return <label><span className="font-bold">{label} <b className={required ? "text-[#9B372C]" : "font-normal text-[#5C6870]"}>（{required ? "必須" : "任意"}）</b></span><select name={name} className={inputClass} aria-invalid={Boolean(error)} aria-describedby={error ? `aoba-${name}-error` : undefined}><option value="">選択してください</option>{options.map((option) => <option key={option}>{option}</option>)}</select>{error && <span id={`aoba-${name}-error`} className="mt-1 block text-sm font-medium text-[#9B372C]">エラー：{error}</span>}</label>; }
function Area({ name, label, required, maxLength, error }: { name: string; label: string; required?: boolean; maxLength: number; error?: string }) { return <label className="md:col-span-2"><span className="font-bold">{label} <b className={required ? "text-[#9B372C]" : "font-normal text-[#5C6870]"}>（{required ? "必須" : "任意"}）</b></span><textarea name={name} maxLength={maxLength} className={`${inputClass} min-h-36`} aria-invalid={Boolean(error)} aria-describedby={error ? `aoba-${name}-error` : undefined} />{error && <span id={`aoba-${name}-error`} className="mt-1 block text-sm font-medium text-[#9B372C]">エラー：{error}</span>}</label>; }
