import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import ContactSection from "@/components/harvest-web-studio/ContactSection";
import FaqSection from "@/components/harvest-web-studio/FaqSection";
import LandingHeader from "@/components/harvest-web-studio/LandingHeader";
import { features, plans, problems } from "@/lib/harvest-web-studio/data";

export const metadata: Metadata = { title: "Harvest Web Studio｜個人事業主向けWebサイト制作", description: "Webサイトが初めての個人事業主・小規模店舗向けに、内容整理から公開まで分かりやすくサポートする架空Web制作サービスのLPです。", openGraph: { title: "Harvest Web Studio｜個人事業主向けWebサイト制作", description: "個人事業主・小規模店舗向けに企画した、ポートフォリオ用の架空Web制作サービスLPです。", type: "website" } };

const steps = [["事業について伺います", "現在のお悩みや目標、お客様についてお聞きします。"], ["伝える内容を整理します", "事業の魅力と、お客様が知りたい情報を言葉にします。"], ["必要なページをご提案します", "目的と予算に合う、過不足のない構成をご提案します。"], ["公開までサポートします", "表示確認や公開作業まで、一つずつご案内します。"]] as const;
const services = [["LP制作", "1つの商品やサービスを詳しく紹介し、お問い合わせや申し込みにつなげる1ページ型サイトです。", "新商品や一つのサービスを伝えたい方"], ["小規模ホームページ", "事業紹介、サービス、プロフィール、お問い合わせなどをまとめたWebサイトです。", "初めて公式サイトを持ちたい方"], ["既存サイト改善", "古いデザインやスマートフォン表示、文章や問い合わせ導線を見直します。", "今のサイトを生かして整えたい方"]] as const;
const works = [["Bakery & Cafe Harvest", "自主制作・架空店舗サイト", "那須高原の架空ベーカリーカフェを想定した、店舗の世界観と季節の魅力を伝えるWebサイトです。", "/works/bakery-cafe-harvest"], ["リラクゼーションサロンWebサイト", "自主制作・架空案件", "初めて訪れる方が、安心して施術内容や料金を確認できるサイトを想定しています。", ""], ["行政書士事務所Webサイト", "自主制作・架空案件", "専門性と相談しやすさを両立した、小規模士業向けWebサイトを想定しています。", ""]] as const;
const flow = ["無料相談", "ヒアリング", "ご提案・お見積もり", "デザイン・制作", "確認・修正", "公開・納品"];

export default function HarvestWebStudioPage() {
  return <div id="top" className="hws-root overflow-x-clip bg-white text-[#1F2937]">
    <style dangerouslySetInnerHTML={{ __html: hwsStyles }} />
    <LandingHeader />
    <main>
      <section className="bg-gradient-to-br from-[#F8FAF8] to-[#EAF2EE] px-5 py-16 md:py-24"><div className="mx-auto grid max-w-[1180px] items-center gap-12 lg:grid-cols-2"><div className="hws-hero"><p className="hws-kicker">個人事業主・小規模店舗向け</p><h1 className="mt-5 text-4xl font-bold leading-tight tracking-tight text-[#2F5145] sm:text-5xl lg:text-6xl">小さな事業に、<br />ちょうどいいWebサイトを。</h1><p className="mt-6 text-lg leading-8 text-[#4B5563]">Webサイトが初めてでも大丈夫です。<br /><br />事業の内容整理からデザイン、制作、公開まで、<br className="hidden sm:block" />分かりやすく丁寧にサポートします。</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href="#contact" className="hws-button text-center">無料相談を申し込む</a><a href="#pricing" className="hws-secondary text-center">制作プランを見る</a></div><ul className="mt-6 grid gap-2 text-sm sm:grid-cols-2">{["初回相談無料", "全国オンライン対応", "埼玉・東京は対面相談可能", "強引な営業なし"].map(x => <li key={x}>✓ {x}</li>)}</ul></div><HeroMock /></div></section>
      <section aria-label="サポート内容" className="border-y border-[#DDE5E1]"><div className="hws-container grid gap-6 py-8 sm:grid-cols-2 lg:grid-cols-4">{[["相談", "初回相談無料", "まずはお話だけでも大丈夫です"], ["全国", "オンライン対応", "ご自宅からご相談いただけます"], ["端末", "スマートフォン対応", "各画面で見やすく整えます"], ["公開", "公開までサポート", "手順を一つずつご案内します"]].map(([icon, title, desc]) => <div key={title} className="flex gap-3"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-[#EAF2EE] text-xs font-bold text-[#2F5145]">{icon}</span><div><h2 className="font-bold">{title}</h2><p className="mt-1 text-sm text-[#4B5563]">{desc}</p></div></div>)}</div></section>
      <Section id="problems" kicker="YOUR CONCERNS" title="こんなお悩みはありませんか？" lead="Webサイトを作る前の迷いも、相談してよいことの一つです。" tone><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{problems.map((x, i) => <Card key={x}><span className="text-sm font-bold text-[#D9834E]">お悩み {String(i + 1).padStart(2, "0")}</span><p className="mt-4 leading-7">{x}</p></Card>)}</div></Section>
      <Section id="service" kicker="SERVICE" title={<>そのお悩みを、<br />一緒に整理します。</>} lead={<>完成した文章や専門知識は必要ありません。<br />お話を伺いながら、事業の魅力や伝える内容を整理します。</>}><div className="grid items-center gap-10 lg:grid-cols-2"><div className="rounded-3xl bg-[#EAF2EE] p-8"><div className="rounded-2xl bg-white p-6 shadow-sm"><div className="mb-5 h-3 w-24 rounded bg-[#3F6B5B]" /><div className="space-y-3"><div className="h-3 w-full rounded bg-[#DDE5E1]"/><div className="h-3 w-4/5 rounded bg-[#DDE5E1]"/><div className="grid grid-cols-2 gap-3 pt-4"><div className="h-24 rounded-xl bg-[#F5F0E8]"/><div className="h-24 rounded-xl bg-[#EAF2EE]"/></div></div></div><p className="mt-4 text-center text-sm text-[#4B5563]">内容を整理し、伝わるページへ</p></div><ol className="space-y-5">{steps.map(([title, desc], i) => <li key={title} className="flex gap-4"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-[#3F6B5B] font-bold text-white">{i + 1}</span><div><h3 className="text-lg font-bold">{title}</h3><p className="mt-1 leading-7 text-[#4B5563]">{desc}</p></div></li>)}</ol></div></Section>
      <Section id="features" kicker="OUR VALUES" title={<>Harvest Web Studioが<br />大切にしている5つのこと</>} tone><div className="flex flex-wrap justify-center gap-5">{features.map(([title, desc], i) => <Card key={title} className="w-full md:w-[calc(50%-0.625rem)] lg:w-[calc(33.333%-0.9rem)]"><span className="text-3xl font-bold text-[#D9834E]">0{i + 1}</span><h3 className="mt-4 text-xl font-bold text-[#2F5145]">{title}</h3><p className="mt-3 leading-7 text-[#4B5563]">{desc}</p></Card>)}</div></Section>
      <Section id="services" kicker="WHAT WE CREATE" title={<>事業に合わせた<br />3つの制作方法</>}><div className="grid gap-5 lg:grid-cols-3">{services.map(([title, desc, fit], i) => <Card key={title}><span className="grid h-12 w-12 place-items-center rounded-xl bg-[#EAF2EE] font-bold text-[#3F6B5B]">0{i + 1}</span><h3 className="mt-5 text-2xl font-bold">{title}</h3><p className="mt-3 leading-7 text-[#4B5563]">{desc}</p><p className="mt-5 rounded-xl bg-[#F8FAF8] p-3 text-sm"><b>向いている方：</b>{fit}</p><a href="#pricing" className="mt-5 inline-block font-bold text-[#2F5145] underline underline-offset-4">対応プランを見る</a></Card>)}</div></Section>
      <Cta title={<>どのプランが合うか<br />分からなくても大丈夫です。</>} body="今のお悩みや、作りたいWebサイトのイメージを伺い、必要な内容をご提案します。" note={<>相談だけでも大丈夫です。<br />まだ依頼を決めていなくても問題ありません。</>} />
      <Section id="works" kicker="WORKS" title="制作事例" tone><div className="grid gap-5 lg:grid-cols-3">{works.map(([title, type, desc, href], i) => <Card key={title} className="overflow-hidden !p-0"><div className={`grid aspect-[16/10] place-items-center ${i === 0 ? "bg-[#F5F0E8]" : "bg-[#EAF2EE]"}`}><span className="text-5xl" aria-hidden="true">{["🥐", "🌿", "📄"][i]}</span></div><div className="p-6"><p className="text-sm font-bold text-[#3F6B5B]">{type}</p><h3 className="mt-2 text-xl font-bold">{title}</h3><p className="mt-3 leading-7 text-[#4B5563]">{desc}</p>{href ? <Link href={href} className="mt-5 inline-block font-bold text-[#2F5145] underline">制作事例を見る</Link> : <span className="mt-5 block text-sm text-[#4B5563]">ポートフォリオ用コンセプト</span>}</div></Card>)}</div><p className="mt-8 text-sm text-[#4B5563]">掲載している事例には、ポートフォリオ用に制作した架空サイトが含まれます。</p></Section>
      <Section id="pricing" kicker="PRICING" title="分かりやすい制作プラン" lead="目的と必要なページに合わせて、3つの参考プランをご用意しました。"><div className="grid gap-5 lg:grid-cols-3">{plans.map((plan) => <article key={plan.name} className={`order-2 rounded-3xl border bg-white p-6 shadow-sm ${plan.featured ? "order-1 border-2 border-[#3F6B5B] lg:order-2" : "border-[#DDE5E1]"} ${plan.name.startsWith("サイト改善") ? "lg:order-1" : "lg:order-3"}`}>{plan.featured && <span className="rounded-full bg-[#D9834E] px-3 py-1 text-xs font-bold text-white">1ページで伝えたい方へ</span>}<h3 className="mt-4 text-xl font-bold">{plan.name}</h3><p className="mt-4 text-3xl font-bold text-[#2F5145]">{plan.price}</p><p className="mt-3 min-h-12 text-sm text-[#4B5563]">{plan.target}</p><ul className="mt-5 space-y-2 border-y border-[#DDE5E1] py-5">{plan.items.map(x => <li key={x}>✓ {x}</li>)}</ul><p className="mt-5"><b>制作期間：</b>{plan.term}</p><a href="#contact" className={plan.featured ? "hws-button mt-6 block text-center" : "hws-secondary mt-6 block text-center"}>このプランを相談する</a></article>)}</div><div className="mt-8 rounded-2xl bg-[#F8FAF8] p-5 text-sm leading-7 text-[#4B5563]"><p>表示料金は、ポートフォリオ用の架空サービスとして設定した参考価格です。</p><p className="mt-2">実際の制作内容、ページ数、機能、素材の準備状況などにより、料金と制作期間は変わります。</p></div></Section>
      <Cta title="料金や制作範囲を一緒に整理します。" body="ご予算が決まっていない段階でも、必要な内容から考えられます。" />
      <Section id="flow" kicker="FLOW" title="ご相談から公開までの流れ" tone><ol className="grid gap-4 md:grid-cols-3 lg:grid-cols-6">{flow.map((x, i) => <li key={x} className="relative rounded-2xl border border-[#DDE5E1] bg-white p-5"><span className="font-bold text-[#D9834E]">STEP {i + 1}</span><h3 className="mt-3 font-bold">{x}</h3></li>)}</ol></Section>
      <Section id="profile" kicker="PROFILE" title={<>ご相談から制作まで、<br />同じ担当者が対応します。</>}><div className="grid items-center gap-10 lg:grid-cols-[.7fr_1.3fr]"><div className="text-center"><Image src="/profile.png" width={260} height={260} sizes="(max-width: 1024px) 200px, 260px" alt="制作者 Takeshi Akaguma" className="mx-auto rounded-full border-8 border-[#EAF2EE]" /></div><div className="space-y-5 leading-8 text-[#4B5563]"><p>システム開発の経験を生かし、分かりやすく使いやすいWebサイト制作に取り組んでいます。</p><p>Webサイト制作が初めての方にも安心していただけるように、専門用語をなるべく使わず、事業内容を整理するところから丁寧に対応します。</p><p className="rounded-2xl bg-[#F8FAF8] p-5"><b className="text-[#2F5145]">大切にしていること</b><br />見た目を整えるだけでなく、誰に何を伝えるWebサイトなのかを一緒に考えることを大切にしています。</p><p>全国オンライン対応<br />埼玉・東京エリアは、日程や場所により対面でのご相談も可能です。</p><Link href="/about" className="hws-secondary inline-block">プロフィールを見る</Link></div></div></Section>
      <FaqSection />
      <Cta title={<>Webサイトについて、<br />まずは話すところから始めませんか？</>} body="制作内容や予算が決まっていなくても問題ありません。今のお悩みや、作りたいWebサイトのイメージをお聞かせください。" note="初回相談無料・相談だけでもOK・強引な営業なし・全国オンライン対応" />
      <ContactSection />
    </main>
    <footer className="bg-[#2F5145] px-5 py-12 text-white"><div className="mx-auto grid max-w-[1180px] gap-8 md:grid-cols-2"><div><p className="text-xl font-bold">Harvest Web Studio</p><p className="mt-2 text-sm text-white/80">個人事業主・小規模事業者向けの架空Webサイト制作サービスLP</p><p className="mt-5 text-sm">Harvest Web Studioは、<br />ポートフォリオ用に企画した架空のサービスです。</p></div><nav aria-label="フッターナビゲーション" className="grid gap-3 md:justify-self-end"><Link href="/">ポートフォリオへ戻る</Link><Link href="/about">制作者について</Link><Link href="/works">その他の制作実績</Link><span className="text-sm text-white/70">プライバシーポリシー：デモのため未設置</span></nav></div><p className="mx-auto mt-10 max-w-[1180px] border-t border-white/20 pt-5 text-sm">© 2026 Harvest Web Studio</p></footer>
  </div>;
}

function Section({ id, kicker, title, lead, tone, children }: { id: string; kicker: string; title: React.ReactNode; lead?: React.ReactNode; tone?: boolean; children: React.ReactNode }) { return <section id={id} className={`hws-section scroll-mt-16 ${tone ? "bg-[#F8FAF8]" : "bg-white"}`}><div className="hws-container"><p className="hws-kicker">{kicker}</p><h2 className="hws-heading">{title}</h2>{lead && <p className="mb-10 mt-5 max-w-3xl text-lg leading-8 text-[#4B5563]">{lead}</p>}<div className={lead ? "" : "mt-10"}>{children}</div></div></section>; }
function Card({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <article className={`hws-card rounded-3xl border border-[#DDE5E1] bg-white p-6 shadow-sm ${className}`}>{children}</article>; }
function Cta({ title, body, note }: { title: React.ReactNode; body: string; note?: React.ReactNode }) { return <section className="bg-[#3F6B5B] px-5 py-16 text-center text-white"><div className="mx-auto max-w-3xl"><h2 className="text-3xl font-bold leading-tight md:text-4xl">{title}</h2><p className="mt-5 text-lg leading-8 text-white/90">{body}</p><a href="#contact" className="mt-7 inline-block rounded-xl bg-white px-7 py-4 font-bold text-[#2F5145] transition hover:-translate-y-0.5 hover:bg-[#F5F0E8] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4">無料で相談してみる</a>{note && <p className="mt-4 text-sm text-white/80">{note}</p>}</div></section>; }
function HeroMock() { return <div className="hws-hero hws-hero-delay rounded-[2rem] bg-[#2F5145] p-4 shadow-xl" role="img" aria-label="小規模事業者向けWebサイトの画面イメージ"><div className="overflow-hidden rounded-2xl bg-white"><div className="flex gap-2 bg-[#F5F0E8] p-3"><i className="h-3 w-3 rounded-full bg-[#D9834E]"/><i className="h-3 w-3 rounded-full bg-[#DDE5E1]"/><i className="h-3 w-3 rounded-full bg-[#DDE5E1]"/></div><div className="grid min-h-[330px] items-center gap-6 p-7 sm:grid-cols-2"><div><div className="h-3 w-24 rounded bg-[#D9834E]"/><div className="mt-5 h-5 w-full rounded bg-[#2F5145]"/><div className="mt-3 h-5 w-4/5 rounded bg-[#3F6B5B]"/><div className="mt-6 h-3 w-full rounded bg-[#DDE5E1]"/><div className="mt-2 h-3 w-3/4 rounded bg-[#DDE5E1]"/><div className="mt-7 h-11 w-36 rounded-xl bg-[#3F6B5B]"/></div><div className="grid aspect-square place-items-center rounded-[40%_60%_45%_55%] bg-[#EAF2EE]"><span className="text-center text-sm font-bold leading-6 text-[#3F6B5B]">あなたの事業に合う<br />伝わるデザイン</span></div></div></div></div>; }

const hwsStyles = `.hws-container{max-width:1180px;margin-inline:auto;padding-inline:20px}.hws-section{padding-block:72px}.hws-kicker{font-size:.75rem;letter-spacing:.18em;font-weight:800;color:#D06F37}.hws-heading{margin-top:12px;font-size:clamp(1.75rem,4vw,2.75rem);line-height:1.25;font-weight:800;color:#2F5145}.hws-button,.hws-secondary{min-height:48px;border-radius:12px;padding:12px 24px;font-weight:700;transition:transform 180ms,background 180ms}.hws-button{background:#3F6B5B;color:white}.hws-button:hover{background:#2F5145;transform:translateY(-2px)}.hws-secondary{border:1px solid #3F6B5B;color:#2F5145;background:white}.hws-secondary:hover{background:#EAF2EE;transform:translateY(-2px)}.hws-card{transition:transform 220ms,box-shadow 220ms}.hws-card:hover{transform:translateY(-3px);box-shadow:0 12px 30px rgba(47,81,69,.1)}.hws-hero{animation:hwsFadeUp 600ms ease both}.hws-hero-delay{animation-delay:160ms}@keyframes hwsFadeUp{from{opacity:0;transform:translateY(14px)}to{opacity:1;transform:none}}@media(min-width:768px){.hws-section{padding-block:104px}.hws-container{padding-inline:28px}}@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto!important}.hws-root *{animation:none!important;transition:none!important}}`;
